#!/usr/bin/env python3

import re
import subprocess
from gradelib import *

import os
os.system("make clean")


r = Runner(save("xv6.out"))

@test(20, "test1")
def test_uthread():
    r.run_qemu(shell_script([
        'test1'
    ]))
    
    print(123)
    if not re.findall("04012a13b860de3fafec2f5afb2a587b5c31b1d06c47fbf3fe2463762828bbf3 1", r.qemu.output, re.M):
        raise AssertionError('Output does not match expected output')

    if not re.findall("04012a13b860de3fafec2f5afb2a587b5c31b1d06c47fbf3fe2463762828bbf3 2", r.qemu.output, re.M):
        raise AssertionError('Output does not match expected output')

    if not re.findall("04012a13b860de3fafec2f5afb2a587b5c31b1d06c47fbf3fe2463762828bbf3 3", r.qemu.output, re.M):
        raise AssertionError('Output does not match expected output')

run_tests()

os.system("make clean")
